name: test & nuget
on: [push]
jobs:
  test-and-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: pwd && ls
      - run: dotnet test
      - run: ./nuget-push.sh ${{ github.ref_name }}
